services:
  - type: web
    name: commute-optimizer
    runtime: php
    repo: https://github.com/ScepticMaku/smart-commute
    branch: master
    buildCommand: |
      composer install --no-dev
      php artisan optimize
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=${PORT:-8080}
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: commute-db
          property: connectionString
    autoDeploy: true

databases:
  - name: commute-db
    databaseName: smart-commute
    user: commute_user
    plan: free